server:
  port: 4018

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  mapper-locations: classpath:mybatis/mapper/**/*.xml       # mapper映射文件

spring:
  application:
    name: connection #这个很重要，这在以后的服务与服务之间相互调用一般都是根据这个name
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  #  mysql 数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.1.200:3306/lossapp?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    druid:
      #初始化连接池大小
      initialSize: 11
      #最大空闲值.当经过一个高峰时间后，连接池可以慢慢将已经用不到的连接慢慢释放一部分，一直减少到maxIdle为止
      minIdle: 3
      #最大活跃数
      maxActive: 50
      #最大建立连接等待时间。如果超过此时间将接到异常。设为－1表示无限制
      maxWait: 60000
      #连接的超时时间，默认为半小时
      minEvictableIdleTimeMillis: 10000
      #开启Web监控
      web-stat-filter:
        enabled: true
        exclusions: /druid/*,*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico
        url-pattern: /*
      #开启监控页面
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: admin123