server:
  port: 4011

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.shusheng.domain  # 所有Entity别名类所在包
  mapper-locations: classpath:mybatis/mapper/**/*.xml       # mapper映射文件

spring:
  application:
    name: Docs #这个很重要，这在以后的服务与服务之间相互调用一般都是根据这个name
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  #  mysql 数据源
  datasource:
    password: root
    username: root
    url: jdbc:mysql://localhost:3306/shusheng?serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  # 配置redis
  redis:
    host: 127.0.0.1
    port: 6379    #  端口
    password: admin   #  密码
    jedis:  #  连接池
      pool:
        max-active: 8  # 连接池最大连接数
        max-wait: -1  #连接池最大阻塞等待时间 （使用负值表示没有限制）
        max-idle: 500  #连接池中的最大空闲连接
        min-idle: 0  #连接池中的最小空闲连接
    lettuce:
      shutdown-timeout: 0
    timeout: 30000  #连接超时时间（毫秒）
    database: 0 # 使用db0数据库进行存储
  # sa-token配置
  sa-token:
    # token名称 (同时也是cookie名称)
    token-name: satoken
    # token有效期，单位s 默认30天, -1代表永不过期
    timeout: 2592000
    # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
    activity-timeout: 30
    # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
    is-concurrent: true
    # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
    is-share: false
    # token风格
    token-style: uuid
  servlet:
    #  上传文件设置
    multipart:
      max-file-size: 10MB  # 单个文件大小
      max-request-size: 100MB  # 单次请求的总文件大小

eureka:
  client:
    registerWithEureka: false # 服务注册开关
    fetchRegistry: false # 服务发现开关
    serviceUrl: # 客户端(服务提供者)注册到哪一个Eureka Server服务注册中心，多个用逗号分隔
      # 单机版 Eureka 服务注册中心
      defaultZone: http://eureka4000.com:4000/eureka,http://eureka3999.com:4000/eureka
  instance:
    instanceId: ${spring.cloud.client.ip-address}/${spring.application.name}:${server.port} # 指定实例ID,就不会显示主机名了
    preferIpAddress: true     #访问路径可以显示IP地址


knife4j:
  enable: true
