server:
  port: 4017

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
#  mapper-locations: classpath:mybatis/mapper/**/*.xml       # mapper映射文件

spring:
  application:
    name: more #这个很重要，这在以后的服务与服务之间相互调用一般都是根据这个name
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  #  mysql 数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    db1: # 本地数据源
      driverClassName: com.mysql.cj.jdbc.Driver
      username: root
      password: root
      url: jdbc:mysql://127.0.0.1:3306/shusheng?serverTimezone=Asia/Shanghai
    db2: # 服务器数据源
      driverClassName: com.mysql.cj.jdbc.Driver
      username: root
      password: root
      url: jdbc:mysql://127.0.0.1:3306/liu?serverTimezone=Asia/Shanghai


